[FIX] CI/CD 검증용 deploy.yml파일 수정

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -35,3 +35,18 @@ jobs:
     - name: Deploy Docker Container
       run: |
         ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} "cd /home/ec2-user/MapDa_Server && docker build -t mapda_server_image . && docker run -d -p 8000:8000 --env-file /home/ec2-user/.env --name mapda_server_container -v /home/ec2-user/secrets:/app/secrets mapda_server_image"
+
+  verification:
+    runs-on: ubuntu-latest
+    needs: deploy
+
+    steps:
+    - name: Verify deployment
+      run: |
+        STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" https://api.mapda.site/docs#/)
+        if [ "$STATUS_CODE" -ne 200 ]; then
+          echo "Verification failed. Received status code: $STATUS_CODE"
+          exit 1
+        else
+          echo "Verification succeeded. Received status code: $STATUS_CODE"
+        fi
