[FIX] 깃허브 액션스, 레디스 Ping-Pong 확인 변경

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -35,7 +35,7 @@ jobs:
     - name: Check Redis status
       run: |
         ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} "
-          REDIS_STATUS=$(redis6-cli ping || echo 'ERROR')
+          REDIS_STATUS=$(echo 'PING' | redis6-cli | grep 'PONG' || echo 'ERROR')
           if [ \"$REDIS_STATUS\" != 'PONG' ]; then
             echo 'Redis is not running. Deployment stopped.';
             exit 1;
